### ISSUE TITLE
Better russian translation

### ISSUE THREAD

**Issue by 1upus** [xy2iii/vitashell-themes#15]
# VitaShell language file ■ класть в "ux0:VitaShell/language/" ■ перевод by lupus

ERROR   = "Ошибка 0x%08X."
OK  = "OK"
YES = "Да"
NO  = "Нет"
CANCEL  = "Отмена"
OFFSET  = "Смещение"
MARK_ALL    = "Выделить всё"
UNMARK_ALL  = "Снять выделение"
MOVE    = "Переместить"
COPY    = "Копировать"
PASTE   = "Вставить"
DELETE  = "Удалить"
RENAME  = "Переименовать"
NEW_FOLDER  = "Создать папку"
FOLDER  = "<Папка>"
COPIED_FILE = "Скопировано файлов: %d."
COPIED_FOLDER   = "Скопировано папок: %d."
COPIED_FILES_FOLDERS    = "Скопировано файлов/папок: %d."
MOVING  = "Перемещение..."
COPYING = "Копирование..."
DELETING    = "Удаление..."
INSTALLING  = "Установка..."
DELETE_FILE_QUESTION    = "Вы действительно хотите удалить этот файл?"
DELETE_FOLDER_QUESTION  = "Вы действительно хотите удалить эту папку?"
DELETE_FILES_FOLDERS_QUESTION   = "Вы действительно хотите удалить эти данные?"
INSTALL_QUESTION    = "Установить данный пакет?"
WIFI_ERROR  = "Для этого действия необходимо активное Wi-Fi подключение."
FTP_SERVER  = "FTP-сервер доступен по адресу:\ftp://%s:%i\'OK' - работа в фоновом режиме.\'Отмена' - остановка сервера."

**Comment by xy2i** [comment]
You could also make a pull request.. Merged.
