### ISSUE TITLE
based on 0.90 chinese language files 

### ISSUE THREAD

**Issue by kavid** [xy2iii/vitashell-themes#52]
[Desktop.zip](https://github.com/xy2iii/vitashell-themes/files/453669/Desktop.zip)

 pls，upload it

**Comment by xy2i** [comment]
https://help.github.com/articles/creating-a-pull-request/

**Comment by kavid** [comment]
base on v0.91
[Desktop.zip](https://github.com/xy2iii/vitashell-themes/files/453964/Desktop.zip)
